### ISSUE TITLE
Investigate/Document using non-Github/non-Netlify auth for Netlify CMS

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/mfocus-tracking#2]
We will be adding sites to Netlify CMS that don't use Github or Netlify, so we need to investigate that method and document it thoroughly, referencing back Netlify's documentation.

**Comment by andreweick** [comment]
After further review, it seems netlify is tuned to work well with GitHub, so I'll keep the repo's on GitHub --

**Comment by andreweick** [comment]
@budparr As I'm leaving the source repos on GITHUB, do you still want to use a tracking repo or do you want me to enter issues / discussion on the source REPO. All things being equal for you, I'd rather have the discussion on the source repo as it is easier for me to track.

**Comment by budparr** [comment]
We use Github for project management and we follow a very specific process that may not be as helpful to you (we write multiple small issues). Only repos in our org are tracked, so one way or another we need the issues in our org. We could move them to our org and move back, if that works for you, but, as I mentioned in the email, we can make this private. It's really just an internal mechanism.

**Comment by andreweick** [comment]
Sounds good -- I'll add comments on the rest of the issues with prirority etc.  Do you want me to make issues or send them to you to make?

**Comment by budparr** [comment]
You can send them to me

**Comment by andreweick** [comment]
(backlog)
