### ISSUE TITLE
Implement "theme" for eick.com

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/mfocus-tracking#5]
We previously created a design for eick.com that's not currently implemented. 

- [ ] retrieve repo info
- [ ] Apply current theme
- [ ] Update to latest Hugo

We may want to refactor the theme, based on some current best practices and our use of modules. Any of that work should be a separate ticket.

**Comment by andreweick** [comment]
bozzetto, A small terracotta sketch of a sculpture: see maquette. :-)

**Comment by andreweick** [comment]
yes, refactor and use 'current best practice'

**Comment by budparr** [comment]
Note: https://github.com/imintel/eick.com/issues/20#issuecomment-655807525
> the theme is in the 'budparr-colors' branch on the repo
